# Generated by Django 3.1.2 on 2021-02-13 14:17

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Prescription_date', models.DateField(auto_now_add=True)),
                ('Prescription_text', models.TextField(blank=True, null=True)),
                ('special_advice', models.TextField(blank=True, null=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Doctor_name', to=settings.AUTH_USER_MODEL)),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Patient_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='DoctorExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=12)),
                ('Profilephoto', models.ImageField(blank=True, null=True, upload_to='Images')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
