# Generated by Django 3.1.2 on 2021-03-02 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0005_auto_20210223_1638'),
    ]

    operations = [
        migrations.AlterField(
            model_name='doctorextra',
            name='Profilephoto',
            field=models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics'),
        ),
        migrations.AlterField(
            model_name='prescription',
            name='Prescription_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
