# Generated by Django 3.1.2 on 2021-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Doctor_app', '0006_auto_20210302_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='prescription',
            name='id',
        ),
        migrations.AddField(
            model_name='prescription',
            name='Prescriptionid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='doctorextra',
            name='Profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
