# Generated by Django 3.1.2 on 2021-03-02 11:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('Patient_app', '0006_auto_20210223_1638'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='LaboratoryExtra',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('joindate', models.DateField(auto_now_add=True)),
                ('mobile', models.CharField(max_length=12)),
                ('Profilephoto', models.ImageField(blank=True, default='default.png', null=True, upload_to='profile_pics')),
                ('Address', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='Patient_app.address')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Lab_report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('report_date', models.DateTimeField(auto_now_add=True)),
                ('report_text', models.TextField(blank=True, null=True)),
                ('Doctor_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lab_Doctor_name', to=settings.AUTH_USER_MODEL)),
                ('Laboratory_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Laboratory_name', to=settings.AUTH_USER_MODEL)),
                ('Patient_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='Lab_Patient_name', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
