# Generated by Django 3.1.2 on 2021-03-02 12:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lab_report',
            name='Test_name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
