# Generated by Django 3.1.2 on 2021-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('laboratory_app', '0002_lab_report_test_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lab_report',
            name='id',
        ),
        migrations.AddField(
            model_name='lab_report',
            name='Lab_reportid',
            field=models.AutoField(default=1, primary_key=True, serialize=False),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='laboratoryextra',
            name='Profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
