# Generated by Django 3.1.2 on 2021-02-16 11:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Patient_app', '0002_auto_20210214_2340'),
    ]

    operations = [
        migrations.CreateModel(
            name='Medical_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('age', models.IntegerField(blank=True, null=True)),
                ('Gender', models.CharField(blank=True, max_length=6, null=True)),
                ('cp', models.IntegerField(blank=True, null=True)),
                ('trestbps', models.IntegerField(blank=True, null=True)),
                ('cholesterol', models.IntegerField(blank=True, null=True)),
                ('restecg', models.IntegerField(blank=True, null=True)),
                ('thalach', models.IntegerField(blank=True, null=True)),
                ('exang', models.BooleanField(blank=True, null=True)),
                ('fbs', models.BooleanField(blank=True, null=True)),
                ('oldpeak', models.FloatField(blank=True, null=True)),
                ('slope', models.IntegerField(blank=True, null=True)),
                ('ca', models.IntegerField(blank=True, null=True)),
                ('thal', models.IntegerField(blank=True, null=True)),
                ('target', models.IntegerField(blank=True, null=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
