# Generated by Django 3.1.2 on 2021-10-28 22:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Patient_app', '0007_patientpasscodes'),
    ]

    operations = [
        migrations.AlterField(
            model_name='patientextra',
            name='Profilephoto',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.DeleteModel(
            name='Medical_details',
        ),
    ]
